PowerFGT/PowerFGT.psm1
for match with API (cmdb is for get and configure) and monitor for get statics/status
=> PowerFGT(.psm1): Add cmdb and monitor (Public) Folder

PowerFGT/Private/RestMethod.ps1, PowerFGT/Public/Connection.ps1
We need to found the csrf token on cookie (ccsrf_token) and set X-CSRFTOKEN to header
=> Connection: Search csrf token and add to header

PowerFGT/Private/Exception.ps1, PowerFGT/Private/RestMethod.ps1, PowerFGT/Public/Connection.ps1
Add support of PowerShell 6 (Core)
=> Fix powershell6

PowerFGT/Private/Exception.ps1
And display warning (and recommanded to use -SkipCertificateCheck)
And Also throw (with message Unable to connect (Certificate)
=> Exception: try to detect if it is a invalid certificat

PowerFGT/Public/Connection.ps1
Add Disconnect-FGT cmdlet
Fix issue when use not standard port
Display connection info (need to be enhance)
=> Enhance connection

PowerFGT/PowerFGT.psm1, PowerFGT/Private/Exception.ps1, PowerFGT/Private/RestMethod.ps1, PowerFGT/Private/SSL.ps1, PowerFGT/Public/Connection.ps1, PowerFGT/Public/cmdb/address.ps1
See https://dscottraynsford.wordpress.com/2017/11/18/auto-formatting-powershell-in-visual-studio-code/
=> Fix indent using Formating from Visual Code Studio

PowerFGT/Private/RestMethod.ps1
Set method to get by default and don't longer need to to specifiy parameter name
=> Enhance FGTRestMethod

PowerFGT/Private/Validate.ps1, PowerFGT/Public/cmdb/address.ps1
Add [Add|Set|Copy|Remove]-FGTAddress
=> Enhance FGTAddress

PowerFGT/Public/cmdb/address.ps1, PowerFGT/Public/cmdb/addressgroup.ps1, PowerFGT/Public/cmdb/dns.ps1, PowerFGT/Public/cmdb/interface.ps1, PowerFGT/Public/cmdb/ippool.ps1, PowerFGT/Public/cmdb/localuser.ps1, PowerFGT/Public/cmdb/policy.ps1, PowerFGT/Public/cmdb/routepolicy.ps1, PowerFGT/Public/cmdb/service.ps1, PowerFGT/Public/cmdb/servicegroup.ps1, PowerFGT/Public/cmdb/staticroute.ps1, PowerFGT/Public/cmdb/vip.ps1, PowerFGT/Public/cmdb/vpnipsec.ps1, PowerFGT/Public/cmdb/zone.ps1
Add Begin/Process/End
Align examples (and add some blank line)
=> Fix indent

PowerFGT/PowerFGT.psd1
14 new cmdlets
- Add 14 new Get-FGT cmdlet for AddressGroup, Policy/rules, Static Route, IP Pool, Vip, Zone...)
- Add -skip parameter to each Get-FGT cmdlet (#40)
=> New Release: 0.2.0

PowerFGT/Public/cmdb/address.ps1, PowerFGT/Public/cmdb/addressgroup.ps1, PowerFGT/Public/cmdb/dns.ps1, PowerFGT/Public/cmdb/ha.ps1, PowerFGT/Public/cmdb/interface.ps1, PowerFGT/Public/cmdb/ippool.ps1, PowerFGT/Public/cmdb/localuser.ps1, PowerFGT/Public/cmdb/policy.ps1, PowerFGT/Public/cmdb/routepolicy.ps1, PowerFGT/Public/cmdb/service.ps1, PowerFGT/Public/cmdb/servicegroup.ps1, PowerFGT/Public/cmdb/staticroute.ps1, PowerFGT/Public/cmdb/systemglobal.ps1, PowerFGT/Public/cmdb/vdom.ps1, PowerFGT/Public/cmdb/vip.ps1, PowerFGT/Public/cmdb/virtual-wan-link.ps1, PowerFGT/Public/cmdb/vpnipsec.ps1, PowerFGT/Public/cmdb/zone.ps1
Add example for each Get-FGT... cmdlets
and fix missing parameter for StaticRoute & VPN IPsec (phase2interface)
=> Enhance skip

PowerFGT/Public/Connection.ps1, PowerFGT/Public/cmdb/firewall/vip.ps1
=> fix misc issue

PowerFGT/Private/RestMethod.ps1, PowerFGT/Public/Connection.ps1, PowerFGT/Public/cmdb/firewall/address.ps1, PowerFGT/Public/cmdb/firewall/addressgroup.ps1, PowerFGT/Public/cmdb/firewall/ippool.ps1, PowerFGT/Public/cmdb/firewall/policy.ps1, PowerFGT/Public/cmdb/firewall/vip.ps1, PowerFGT/Public/cmdb/router/policy.ps1, PowerFGT/Public/cmdb/router/static.ps1, PowerFGT/Public/cmdb/system/dns.ps1, PowerFGT/Public/cmdb/system/global.ps1, PowerFGT/Public/cmdb/system/ha.ps1, PowerFGT/Public/cmdb/system/interface.ps1, PowerFGT/Public/cmdb/system/vdom.ps1, PowerFGT/Public/cmdb/system/virtual-wan-link.ps1, PowerFGT/Public/cmdb/system/zone.ps1, PowerFGT/Public/cmdb/user/local.ps1, PowerFGT/Public/cmdb/vpn/ipsec/phase1-interface.ps1, PowerFGT/Public/cmdb/vpn/ipsec/phase2-interface.ps1, README.md
Add -vdom parameter for all cmdlet 
it is now possible to select a vdom when get/set/add...
=> Add VDOM (experimental) support

PowerFGT/PowerFGT.psd1
- Adding support of (experimental) VDOM support using -vdom for each cmdlet (#47)
- Add X new Get-FGT cmdlets : Virtual WAN Link (SDWAN), Systam HA/Global/VDOM ... (#43 #44)
- Rename cmdlet (break compability) for following api structure (Get-FGTAddress => Get->FGTFirewallAddress...)
(#46)
- Adding Multi Connection support (#49)
=> new release 0.3.0 !

PowerFGT/Private/Validate.ps1, PowerFGT/Public/cmdb/firewall/vip.ps1, README.md
You can now add and Remove FirewallVip only support static-nat (One to One) (Part of #51)
=> VIP: Add Add/Remove FGTFirewallVIP

PowerFGT/Private/Validate.ps1, PowerFGT/Public/cmdb/firewall/addressgroup.ps1
You can now Add, Copy and Remove AddressGroup and also Add and Remove AddressGroup Member (Part of #51)
=> AddressGroup: Add/Copy/Remove Address Group (and Member)

PowerFGT/Public/cmdb/firewall/service/custom.ps1, PowerFGT/Public/cmdb/firewall/service/group.ps1
Missiong Vdom and Multi Connection parameter
=> Fix Service

PowerFGT/Public/cmdb/firewall/address.ps1, PowerFGT/Public/cmdb/firewall/addressgroup.ps1, PowerFGT/Public/cmdb/firewall/ippool.ps1, PowerFGT/Public/cmdb/firewall/policy.ps1, PowerFGT/Public/cmdb/firewall/service/custom.ps1, PowerFGT/Public/cmdb/firewall/service/group.ps1, PowerFGT/Public/cmdb/firewall/vip.ps1, PowerFGT/Public/cmdb/router/policy.ps1, PowerFGT/Public/cmdb/router/static.ps1, PowerFGT/Public/cmdb/system/dns.ps1, PowerFGT/Public/cmdb/system/global.ps1, PowerFGT/Public/cmdb/system/ha.ps1, PowerFGT/Public/cmdb/system/interface.ps1, PowerFGT/Public/cmdb/system/vdom.ps1, PowerFGT/Public/cmdb/system/virtual-wan-link.ps1, PowerFGT/Public/cmdb/system/zone.ps1, PowerFGT/Public/cmdb/user/local.ps1, PowerFGT/Public/cmdb/vpn/ipsec/phase1-interface.ps1, PowerFGT/Public/cmdb/vpn/ipsec/phase2-interface.ps1
Use new filtering 'API' (-filter from Invoke-FGTRestMethod)
=> Use new filtering

PowerFGT/Public/cmdb/firewall/vip.ps1
For only map port (TCP/UDP/SCTP/ICMP)
=> VIP: Add Port Forwarding

README.md
- Update list of available command
- Add Example for AddressGroup, VIP, Policy, Deploy-VM...
=> Update README.(md) for 0.4.0

PowerFGT/PowerFGT.psd1, README.md
- Enhance Filtering (using directly API) (#58, #62)
- Add Add/Set/Remove Address Group (#57)
- Add Add/Set/Remove Virtual IP (VIP) (#54)
- Add Add/Remove Firewall Policy {#65, #68 )
- Add Deploy-FGTVm for deploy FortiGate vapp (#34)
- Add Timeout setting for Connect-FGT (and Invoke-FGTRestMethod) (#56)
=> New release 0.4.0 !

PowerFGT/Public/Deploy.ps1
Fix require of VMware.PowerCLI when use PowerFGT (it is not mandatory, only need for Deploy-FGTVm)
Fix typo on example about deploy-vm (wrong parameter)
Fix #71
=> Fix Deploy-FGTVM

PowerFGT/PowerFGT.psd1, README.md
Fix required VMware.PowerCLI module (not mandatory)
Fix typo on Deploy-FGTVm
Add platyPS docs
=> new release 0.4.1

PowerFGT/Public/cmdb/firewall/policy.ps1, PowerFGT/Public/cmdb/system/settings.ps1
Allow to add unnamed policy if gui-allow-unnamed-policy allow this (or generate throw)
Add Get-FGTSystemSettings for get this setting
Fix #75
=> Allow unnamed policy

PowerFGT/Private/Confirm.ps1, PowerFGT/Public/cmdb/firewall/address.ps1
Fix issue found when write pester test #96
=> Fix Address cmdlet issue

Tests/.gitignore, Tests/README.md, Tests/common.ps1, Tests/credential.example.ps1, Tests/integration/Connection.Tests.ps1, Tests/integration/FirewallAddress.Tests.ps1, Tests/integration/FirewallAddressGroup.Tests.ps1, Tests/integration/FirewallPolicy.Tests.ps1, Tests/integration/FirewallVip.Tests.ps1
=> Add Pester Tests

PowerFGT/Public/Connection.ps1, PowerFGT/Public/cmdb/firewall/address.ps1, PowerFGT/Public/cmdb/firewall/addressgroup.ps1, PowerFGT/Public/cmdb/firewall/policy.ps1, PowerFGT/Public/cmdb/firewall/vip.ps1, Tests/integration/Connection.Tests.ps1, Tests/integration/FirewallAddress.Tests.ps1, Tests/integration/FirewallAddressGroup.Tests.ps1, Tests/integration/FirewallPolicy.Tests.ps1, Tests/integration/FirewallVip.Tests.ps1
and fix PSSA Warning about this... 
(break compability...)
=> Add ShouldProcess support

.vscode/PSScriptAnalyzerSettings.psd1, PowerFGT/Private/SSL.ps1, PowerFGT/Public/Deploy.ps1, PowerFGT/Public/cmdb/firewall/policy.ps1
=> PSSA(Settings): remove extra comma (All tests is bypass...)

PowerFGT/Private/Confirm.ps1, PowerFGT/Public/cmdb/firewall/address.ps1, README.md, Tests/integration/FirewallAddress.Tests.ps1
Added FQDN addresstype to Get-FGTFirewallAddress and Add-FGTFirewallAddress using dynamic parameters.
=> added FQDN addresstype

PowerFGT/Public/cmdb/firewall/policy.ps1, Tests/integration/FirewallPolicy.Tests.ps1
=> Firewall(Policy): Add PolicyID parameter (and Tests)

PowerFGT/Public/Connection.ps1, Tests/integration/Connection.Tests.ps1
Get current firmware version and set on connection(.version) info 
for add after some check (like visibility not longer supported with FortiOS 6.4.x)
=> Add Version on Connection info

Tests/common.ps1, Tests/credential.example.ps1, Tests/integration/Connection.Tests.ps1, Tests/integration/FirewallAddress.Tests.ps1, Tests/integration/FirewallAddressGroup.Tests.ps1, Tests/integration/FirewallPolicy.Tests.ps1, Tests/integration/FirewallProxyAddress.Tests.ps1, Tests/integration/FirewallProxyAddressGroup.Tests.ps1, Tests/integration/FirewallProxyPolicy.Tests.ps1, Tests/integration/FirewallVip.Tests.ps1, Tests/integration/FirewallVipGroup.Tests.ps1
Update test suite for use Pester v5(.1)
also add support of port parameter !
=> Migrate to Pester v5

PowerFGT/Public/cmdb/firewall/vip.ps1
=> Fix protocol parameter for VIP

PowerFGT/Public/Connection.ps1, Tests/integration/Connection.Tests.ps1
=> Fix connection when post-login-banner is enable

Tests/integration/FirewallProxyPolicy.Tests.ps1
Need to specify always a srcintf for transparent-web
=> ProxyPolicy(Tests): Fix Tests with FortiOS 7.0.x

PowerFGT/Private/RestMethod.ps1
Can be use full for same API with depth > 2
also convert only one
issue Reported by Ari Rouhiainen
=> RestMethod: Add depth 10 for ConvertTo-Json

PowerFGT/Public/cmdb/system/global.ps1, PowerFGT/Public/cmdb/system/settings.ps1, Tests/integration/SystemGlobal.Tests.ps1, Tests/integration/SystemSettings.Tests.ps1
You can modified Global or Settings
=> System: Add Set-FGTSystem* for modified  Settings

PowerFGT/Public/cmdb/system/interface.ps1, Tests/integration/SystemInterface.Tests.ps1
Add Add-FGTSystemInterfaceMember and Remove-FGTSystemInterfaceMember for append/remove settings (only support allowaccess for the moment)
=> SystemInterfaceMember (Add/Remove)

PowerFGT/Public/monitor/system/config/backup.ps1, Tests/integration/Connection.Tests.ps1
=> Monitor(Backup): Add Get-FGTMonitorSystemConfigBackup

PowerFGT/Public/cmdb/firewall/policy.ps1, Tests/integration/FirewallPolicy.Tests.ps1
=> Enhance Unnamed Policy (Tests)

PowerFGT/Public/monitor/system/firmware.ps1, Tests/integration/Connection.Tests.ps1
=> Add Get-MonitorSystemFirmware (and Upgrade-Paths)

PowerFGT/Public/monitor/vpn/ipsec.ps1, PowerFGT/Public/monitor/vpn/ssl.ps1, Tests/integration/Connection.Tests.ps1
Add Get-FGTMonitorVpnIPsec and Get-FGTMonitorVpnSsl
Fix #94
=> Add Get-FGTMonitorVPN (IPSec/SSL)

.github/workflows/release.yml
Use pwsh shell,
Update checkout (v3)
Add tweet when new release
=> Update GitHub Actions workflow for release

PowerFGT/Public/Connection.ps1
Add Serial Number to the connection information
=> Add Serial Number to Connection info

PowerFGT/Public/cmdb/system/dns-server.ps1, Tests/integration/Connection.Tests.ps1
=> DnsServer(system): Add Get-FGTSystemDnsServer

PowerFGT/Public/monitor/system/ha.ps1, Tests/integration/Connection.Tests.ps1
=> HA(Monitor): Add Get-FGTMonitorSystemHAPeer and Checksum

PowerFGT/Public/monitor/firewall/policy.ps1, Tests/integration/Connection.Tests.ps1
With Multi Connection tests
you can also filter by policyid
=> Policy(monitor): Add Get-FGTMonitorFirewallPolicy

PowerFGT/Public/monitor/router/ipv4.ps1, Tests/integration/Connection.Tests.ps1
…4 Routing
add also multi test connection test
=> Router/IPv4(monitor): Add Get-FGTMonitorRouterIPv4 for get active IPv4

.github/workflows/release.yml
it is compatible with APIv2 and use PowerShell :)
=> release(gba): use BlueBirdPS for tweet

.github/workflows/platyPS.yaml
using platyPS and GitHub Actions
=> platyPS(GBA): Add Update of docs workflow

Tests/common.ps1, Tests/credential.ci.ps1, Tests/credential.example.ps1, Tests/integration/Connection.Tests.ps1, Tests/integration/FirewallProxyPolicy.Tests.ps1, Tests/integration/SystemGlobal.Tests.ps1
When use with some CI(like azure pipelines) and fix typo/bug
=> Enhance pester Tests

PowerFGT/Public/Connection.ps1
=> Add support of Connection with FortiToken

PowerFGT/Public/Connection.ps1
For the first connection with FortiOS 7.2.x, add licence
=> Connection: Add Licence when connect

PowerFGT/Public/log/traffic.ps1
Fix support for FortiAnalyzer
TODO :
=> Enhance Get-FGTLogTraffic

PowerFGT/Public/monitor/network/arp.ps1, Tests/integration/Connection.Tests.ps1
=> Add Get-FGTMonitorNetworkARP for get ARP Table

PowerFGT/Public/cmdb/firewall/policy.ps1
=> policy(move): add missing multi connection support

PowerFGT/Public/Connection.ps1
now it is ccsrftoken_XXX with XXX port number...
=> Connection: Fix get CCSRF Token with FortiOS 7.2.4 (or 7.4.x)

PowerFGT/Public/cmdb/firewall/policy.ps1, PowerFGT/Public/cmdb/firewall/vip.ps1, Tests/integration/FirewallVip.Tests.ps1
Add arpreply and data parameter
=> VIP: Enhance (Add Arp Reply and Data Parameters)

PowerFGT/Public/log/traffic.ps1
=> traffic(log): fix typo for filter_value of dstip

PowerFGT/Public/cmdb/firewall/policy.ps1, Tests/integration/FirewallPolicy.Tests.ps1
for configure FGT Firewall Policy (name, src/dst intf/addr...)
Fix #230
=> Add Set-FGTFirewallPolicy cmdlet

PowerFGT/Public/cmdb/firewall/policy.ps1, PowerFGT/Public/cmdb/system/settings.ps1, Tests/integration/FirewallPolicy.Tests.ps1, Tests/integration/FirewallProxyAddress.Tests.ps1, Tests/integration/FirewallProxyAddressGroup.Tests.ps1, Tests/integration/FirewallProxyPolicy.Tests.ps1, Tests/integration/FirewallVipGroup.Tests.ps1, Tests/integration/RouterStatic.Tests.ps1, Tests/integration/SystemGlobal.Tests.ps1, Tests/integration/SystemSettings.Tests.ps1, Tests/integration/VpnIPsecPhase1Interface.Tests.ps1, Tests/integration/VpnIPsecPhase2Interface.Tests.ps1
After update CI image, update/enhance Tests...
=> Tests: Update for support last 7.2.(7) release

PowerFGT/Public/cmdb/firewall/policy.ps1, PowerFGT/Public/cmdb/system/global.ps1, PowerFGT/Public/cmdb/system/settings.ps1, Tests/integration/FirewallAddress.Tests.ps1, Tests/integration/FirewallAddressGroup.Tests.ps1, Tests/integration/FirewallPolicy.Tests.ps1, Tests/integration/FirewallProxyAddress.Tests.ps1, Tests/integration/FirewallProxyAddressGroup.Tests.ps1, Tests/integration/FirewallProxyPolicy.Tests.ps1, Tests/integration/FirewallVipGroup.Tests.ps1, Tests/integration/SystemGlobal.Tests.ps1, Tests/integration/SystemSettings.Tests.ps1, Tests/integration/VpnIPsecPhase1Interface.Tests.ps1, Tests/integration/VpnIPsecPhase2Interface.Tests.ps1, azure-pipelines.yml
=> Add Support of FortiOS 7.4.x

PowerFGT/PowerFGT.psd1, README.md
* Traffic(Log): Fix typo by @alagoutte in https://github.com/FortiPower/PowerFGT/pull/222
* traffic(log): fix typo for filter_value of dstip by @alagoutte in https://github.com/FortiPower/PowerFGT/pull/229
* Add -meta parameter to get q_ info by @alagoutte in https://github.com/FortiPower/PowerFGT/pull/226
* Adding MAC Address Firewall Address type by @alagoutte in https://github.com/FortiPower/PowerFGT/pull/235
* Add -data parameter for Add/Get function by @alagoutte in https://github.com/FortiPower/PowerFGT/pull/234
* Policy: Add Security Profile Support by @alagoutte in https://github.com/FortiPower/PowerFGT/pull/238
* Add Set-FGTFirewallPolicy cmdlet by @alagoutte in https://github.com/FortiPower/PowerFGT/pull/239
* Add Get Log Settings by @alagoutte in …
=> Release 0.8.0

PowerFGT/Public/monitor/system/interface.ps1, README.md, Tests/integration/Connection.Tests.ps1
You can add also vlan, aggregate info and select scope (vdom/global)
Fix : #269
=> Add Get-FGTMonitorSystemInterface

PowerFGT/Public/monitor/system/dhcp.ps1, README.md, Tests/integration/Connection.Tests.ps1
update README.md and add multi connection Tests
=> DHCP(Monitor/System): Add Get-FGTMonitorSystemDHCP for get DHCP leases

PowerFGT/Public/cmdb/system/virtual-switch.ps1, README.md, Tests/integration/Connection.Tests.ps1
For get virtual (hardware) switch information (Physical-switch, vlan, port, span)
Fix #256
=> VirtualSwitch(Admin): Add Get-FGTSystemVirtualSwitch with Tests

PowerFGT/Public/cmdb/router/ospf.ps1, README.md, Tests/integration/Connection.Tests.ps1, Tests/integration/RouterOSPF.Tests.ps1
for Get and Set (Configure) OSPF
=> OSPF: Add Get/Set-FGTRouterOSPF

PowerFGT/Public/monitor/router/bgp.ps1, PowerFGT/Public/monitor/router/ospf.ps1, README.md, Tests/integration/Connection.Tests.ps1
For get status of BGP / OSPF Neighbors
=> Monitor: Get Monitor Router BGP/OSPF Neighbors

PowerFGT/Public/cmdb/user/local.ps1, README.md, Tests/integration/UserLocal.Tests.ps1
When it is add (enable by default)
and also update doc...)
=> Fix UserLocal status

PowerFGT/Public/cmdb/switch/fortilink-settings.ps1, PowerFGT/Public/cmdb/switch/global.ps1, PowerFGT/Public/cmdb/switch/lldp-profile.ps1, PowerFGT/Public/cmdb/switch/lldp-settings.ps1, PowerFGT/Public/cmdb/switch/managed-switch.ps1, PowerFGT/Public/cmdb/switch/snmp-community.ps1, PowerFGT/Public/cmdb/switch/stp-instance.ps1, PowerFGT/Public/cmdb/switch/stp-settings.ps1, PowerFGT/Public/cmdb/switch/switch-group.ps1, PowerFGT/Public/cmdb/switch/switch-profile.ps1, PowerFGT/Public/cmdb/switch/system.ps1, PowerFGT/Public/cmdb/switch/vlan-policy.ps1, Tests/integration/Connection.Tests.ps1
For Global FortiLink...
Fix #292
=> Add Get-Switch(-Controller) cmdlet

PowerFGT/Public/monitor/system/interface/transceivers.ps1, README.md, Tests/integration/Connection.Tests.ps1
Add Get-FGTMonitorSystemInterfaceTransceivers information
=> Transceiver(Monitor): Add Get Transceiver info

PowerFGT/PowerFGT.psd1, README.md
Add Wireless / Switch and update list of command
=> Update readme 0.9.1

PowerFGT/Public/Connection.ps1, Tests/integration/SystemGlobal.Tests.ps1, Tests/integration/SystemSettings.Tests.ps1
Change with Connection (return json for status)
and change with VPN SSL.....
=> Fix Tests when use FortiOS 7.6.3
